openapi: 3.0.0
info:
  version: "1.0.0"
  title: annotaurus API
  description: RESTful API exposing ingest functionality of annotaurus.
  contact:
    email: ghp@lum.ai
# https://swagger.io/docs/specification/api-host-and-base-path/
servers:
 #- url: "http://localhost:9000/api"
 - url: /api
tags:
  - name: "annotation"
    description: |
      Operations related to text annotation (parsing, etc.).
  - name: "config"
    description: |
      Endpoints for inspecting project config.
paths:
              
  /clu/annotate:
    get:
      tags:
        - "annotate"
      summary: |
        Annotate text.
      description: |
        Annotate (tokenize, tag, parse, etc.) text.
      parameters:
        - name: text
          in: query
          description: |
            The text to be annotated.
          required: true
          schema:
            type: string
        #  example:
      responses:
        '200':
          description: Annotated text in the form of Document JSON.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CluDocument"

    post:
      tags:
        - "annotate"
      summary: |
        Accepts raw text and produces a `org.clulab.processors.Document`
      description: |
        Accepts raw text and produces a `org.clulab.processors.Document`
      requestBody:
        description: |
          raw text to annotate.
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Annotated text in the form of Document JSON.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CluDocument"        
components:
  schemas:

    CluDocument:
      type: object
      required:
        - id
        - text
        - sentences
      properties:
        id:
          type: integer
          format: int64
          description: |
            The equivalence hash for this org.clulab.processors.Document.
        text:
          type: string
          description: |
            The original text from which this Document was produced.
        sentences:
          type: array
          description: |
            array of org.clulab.processors.Sentence.
          items:
            $ref: "#/components/schemas/CluSentence"

    CluSentence:
      type: object
      required:
        - words
        - startOffsets
        - endOffsets
  #      - raw
  #      - tags
  #      - lemmas
  #      - entities
  #      - norms
  #      - chunks
        - graphs
      properties:
        words:
          type: array
          description: |
            The tokens for this sentence.
          items:
            type: string
        lemmas:
          type: array
          description: |
            The lemma form of each token in this sentence.
          items:
            type: string
        tags:
          type: array
          description: |
            The part of speech tag for each token in this sentence.
          items:
            type: string
        chunks:
          type: array
          description: |
            The BIO-style chunk label designating a coarse XP assignment for each token in this sentence.
          items:
            type: string
        entities:
          type: array
          description: |
            The BIO-style entity label for each token in this sentence.
          items:
            type: string
        startOffsets:
          type: array
          description: |
            The character-based start offset for each token in this sentence.
          items:
            type: integer
            format: int32
        endOffsets:
          type: array
          description: |
            The character-based end offset for each token in this sentence.
          items:
            type: integer
            format: int32
        graphs:
          $ref: "#/components/schemas/CluGraphMap"

    CluGraphMap:
      type: object
      description: |
        Map of graph name -> DirectedGraph.
      additionalProperties:
        type: string
        description: |
          The name of a DirectedGraph.

    CluDirectedGraph:
      type: object
      properties:
        edges:
          type: array
          description: |
            A edges comprising this graph.
          items:
            $ref: "#/components/schemas/Edge"
        roots:
          type: array
          description: |
            The token indices corresponding to the root nodes for this DirectedGraph.
          items:
            type: integer
            format: int32

    CluEdge:
      type: object
      required:
        - source
        - destination
        - relation
      properties:
        source:
          type: integer
          format: int32
          description: |
            The token index for the source vertex.
        destination:
          type: integer
          format: int32
          description: |
            The token index for the destination vertex.
        relation:
          type: string
          description: |
            The relation to which this Edge corresponds.