name: Linting (scala)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Lint check via scalafmt
      run: sbt scalafmtCheckAll
