name: Linting (scala)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate short commit hash
      id: sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "11"
    - name: Lint check via scalafmt
      run: sbt scalafmtCheckAll
