# dockerless action
name: Project CI (Python)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:

  python:
    name: "Python library"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [ '3.9' ]
        # exclude:
        #   - os: macos-latest
        #     python-version: '3.8'
        #   - os: windows-latest
        #     python-version: '3.6'
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        #architecture: x64
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"

    # Library
    - name: "Install library"
      working-directory: ./python
      run: |
        pip install ".[all]"
    # Tests
    - name: "Tests and coverage"
      working-directory: ./python
      run: |
        pytest