name: Tests (scala)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # see https://github.com/actions/setup-java#testing-against-different-java-versions
      matrix:
        os: [ "ubuntu-latest" ] #, macos-latest, windows-latest]
        distribution: [ "temurin" ]
        #distribution: [ "zulu", "temurin" ]
        #java: [ "8", "11", "17" ]
        java: ["11"]
    name: Tests (scala)
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Run tests
      run: sbt test
